// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHqjTDi0xvohPrFe2iqyX0BLxKGMWZ-k',
    appId: '1:144716768957:web:be9654a11022103b3439d4',
    messagingSenderId: '144716768957',
    projectId: 'bir-umma-f130d',
    authDomain: 'bir-umma-f130d.firebaseapp.com',
    storageBucket: 'bir-umma-f130d.appspot.com',
    measurementId: 'G-660EVD3661',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxY4_CaXQb-QtF6zflhgccpKz_GbYAZc',
    appId: '1:144716768957:android:b345694f7e85376d3439d4',
    messagingSenderId: '144716768957',
    projectId: 'bir-umma-f130d',
    storageBucket: 'bir-umma-f130d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KAj2reFmknXWTXHtjCyQcm2gU_Siteo',
    appId: '1:144716768957:ios:2870737ceded57ac3439d4',
    messagingSenderId: '144716768957',
    projectId: 'bir-umma-f130d',
    storageBucket: 'bir-umma-f130d.appspot.com',
    iosClientId: '144716768957-bbjhetqrrmgjq33kp37uh7di5984bq4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.birUmma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KAj2reFmknXWTXHtjCyQcm2gU_Siteo',
    appId: '1:144716768957:ios:2870737ceded57ac3439d4',
    messagingSenderId: '144716768957',
    projectId: 'bir-umma-f130d',
    storageBucket: 'bir-umma-f130d.appspot.com',
    iosClientId: '144716768957-bbjhetqrrmgjq33kp37uh7di5984bq4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.birUmma',
  );
}
